# Site settings
title: Didgerati
description: >- # this means to ignore newlines until "baseurl:"
  breathe.</br> 
  sing.</br>
  repeat.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://didgerati.com" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: "UA-167572615-1"


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : rodin
brand:
  name     : Didgerati
  logo_sm  : /assets/didgerati_breve.png
  logo     : /assets/didgerati_alpha.png
  image    : /assets/treesun.png
  email    :
  github   : 
  twitter  : 
  linkedin : 
  facebook : 

# Posts default Permalink
permalink: /:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
